detect:
  lane:
     yellow:
      hue_l: 0
      hue_h: 0
      saturation_l: 0
      saturation_h: 0
      lightness_l: 85
      lightness_h: 180
     white:
      hue_l: 27
      hue_h: 35
      saturation_l: 230
      saturation_h: 255
      lightness_l: 160
      lightness_h: 255
